import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Node = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<Node>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
